### PR TITLE
fit() no longer drops the epi_workflow class

### LINKED ISSUE #363: `fit.epi_workflow` silently drops `epi_workflow` class when built or fit on a non-`epi_df` or non-`epi_recipe` in most cases
I assume this will cause issues down the line when users are unexpectedly being missing out on slathering, or even earlier in the operation any `step_epi*`.

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
library(epipredict)
#> Loading required package: epiprocess
#> Registered S3 method overwritten by 'tsibble':
#>   method               from 
#>   as_tibble.grouped_df dplyr
#> 
#> Attaching package: 'epiprocess'
#> The following object is masked from 'package:stats':
#> 
#>     filter
#> Loading required package: parsnip
#> Registered S3 method overwritten by 'epipredict':
#>   method            from   
#>   print.step_naomit recipes
library(testthat)
#> 
#> Attaching package: 'testthat'
#> The following object is masked from 'package:dplyr':
#> 
#>     matches

tbl <- tibble::tibble(
  geo_value = 1,
  time_value = 1:100,
  x = 1:100,
  y = x + rnorm(100L)
)
edf <- as_epi_df(tbl)

rec_tbl <- recipe(y ~ x, data = tbl)
rec_edf <- recipe(y ~ x, data = edf)
erec_tbl <- epi_recipe(y ~ x, data = tbl) # warning, good; not testing further; why not error though?
#> Warning: epi_recipe has been called with a non-epi_df object, returning a
#> regular recipe. Various step_epi_* functions will not work.
erec_edf <- epi_recipe(y ~ x, data = edf)

ewf_rec_tbl <- epi_workflow(rec_tbl, linear_reg())
ewf_rec_edf <- epi_workflow(rec_edf, linear_reg())
ewf_erec_edf <- epi_workflow(erec_edf, linear_reg())

# above are all epi_workflows:

expect_s3_class(ewf_rec_tbl, "epi_workflow")
expect_s3_class(ewf_rec_edf, "epi_workflow")
expect_s3_class(ewf_erec_edf, "epi_workflow")

# but fitting drops the class or generates errors in many cases:

ewf_rec_tbl %>% fit(tbl) %>% class()
#> [1] "workflow"
ewf_rec_tbl %>% fit(edf) %>% class()
#> [1] "workflow"
ewf_rec_edf %>% fit(tbl) %>% class()
#> [1] "workflow"
ewf_rec_edf %>% fit(edf) %>% class()
#> [1] "workflow"
ewf_erec_edf %>% fit(tbl) %>% class()
#> Error in if (new_meta != old_meta) {: argument is of length zero
ewf_erec_edf %>% fit(edf) %>% class()
#> [1] "epi_workflow" "workflow"
```

<sup>Created on 2024-07-18 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by dajmcdon**
### Checklist

Please:

- [x] Make sure this PR is against "dev", not "main".
- [x] Make sure to bump the version number in `DESCRIPTION` and `NEWS.md`.
      Always increment the patch version number (the third number), unless you are
      making a release PR from dev to main, in which case increment the minor
      version number (the second number).
- [x] Describe changes made in NEWS.md, making sure breaking changes
      (backwards-incompatible changes to the documented interface) are noted.
      Collect the changes under the next release number (e.g. if you are on
      0.7.2, then write your changes under the 0.8 heading).

### Magic GitHub syntax to mark associated Issue(s) as resolved when this is merged into the default branch

- Resolves #363

### CODE REVIEW

File: tests/testthat/test-epi_workflow.R [hunk 1]
```diff
@@ -105,3 +105,40 @@ test_that("forecast method errors when workflow not fit", {
...
+    geo_value = 1,
+    time_value = 1:100,
+    x = 1:100,
+    y = x + rnorm(100L)
+  )
+  edf <- as_epi_df(tbl)
+
+  rec_tbl <- recipe(y ~ x, data = tbl)
+  rec_edf <- recipe(y ~ x, data = edf)
+  expect_snapshot_warning(erec_tbl <- epi_recipe(y ~ x, data = tbl))
```
Comment (dshemetov) [inline tests/testthat/test-epi_workflow.R:123]: suggest(non-blocking): error here like @brookslogan suggests in https://github.com/cmu-delphi/epipredict/issues/363 

main reason: while this might be convenient for some users, any downstream code will now have to do a boilerplate check whether the return is a recipe or an epi_recipe and implement the error itself, if it depends on it. seems better to just do that upstream.

**Review by dshemetov — APPROVED** [review]
Seems fine to me, modulo a small non-blocking suggestion to error when epi_recipe is given non-epi_df data instead of decaying to recipe.

File: tests/testthat/test-epi_workflow.R (hunk 1 above)
Comment (dajmcdon) [reply tests/testthat/test-epi_workflow.R:123]: If you insist...
