### PR TITLE
doc: fix step_lag_difference example

### LINKED ISSUE #347: `step_lag_difference` example should be a little clearer
This example should filter out `NA`'s so it demonstrates the behavior better https://cmu-delphi.github.io/epipredict/reference/step_lag_difference.html

```
#> Warning: ! No training data was supplied to `prep()`.
#> ! Unlike a <recipe>, an <epi_recipe> does not
#> ! store the full template data in the object.
#> ! Please supply the training data to the `prep()` function,
#> ! to avoid addtional warning messages.
#> An `epi_df` object, 20,496 x 8 with metadata:
#> * geo_type  = state
#> * time_type = day
#> * as_of     = 2022-05-31 19:08:25.791826
#> 
#> # A tibble: 20,496 × 8
#>    geo_value time_value case_rate death_rate lag_diff_7_case_rate
#>  * <chr>     <date>         <dbl>      <dbl>                <dbl>
#>  1 ak        2020-12-31      35.9      0.158                   NA
#>  2 al        2020-12-31      65.1      0.438                   NA
#>  3 ar        2020-12-31      66.0      1.27                    NA
#>  4 as        2020-12-31       0        0                       NA
#>  5 az        2020-12-31      76.8      1.10                    NA
#>  6 ca        2020-12-31      96.0      0.751                   NA
#>  7 co        2020-12-31      35.8      0.649                   NA
#>  8 ct        2020-12-31      52.1      0.819                   NA
#>  9 dc        2020-12-31      31.0      0.601                   NA
#> 10 de        2020-12-31      65.2      0.807                   NA
#> # ℹ 20,486 more rows
#> # ℹ 3 more variables: lag_diff_14_case_rate <dbl>, lag_diff_7_death_rate <dbl>,
#> #   lag_diff_14_death_rate <dbl>
```

### PR DESCRIPTION
**Pull request by dshemetov**
### Checklist

Please:

- [x] Make sure this PR is against "dev", not "main".
- [x] Request a review from one of the current epipredict main reviewers:
      dajmcdon.
- [x] Make sure to bump the version number in `DESCRIPTION` and `NEWS.md`.
      Always increment the patch version number (the third number), unless you are
      making a release PR from dev to main, in which case increment the minor
      version number (the second number).
- [x] Describe changes made in NEWS.md, making sure breaking changes
      (backwards-incompatible changes to the documented interface) are noted.
      Collect the changes under the next release number (e.g. if you are on
      0.7.2, then write your changes under the 0.8 heading).
- [x] Consider pinning the `epiprocess` version in the `DESCRIPTION` file if
  - You anticipate breaking changes in `epiprocess` soon
  - You want to co-develop features in `epipredict` and `epiprocess`

### Change explanations for reviewer

Adds  step_epi_naomit to get rid of NAs.

### Magic GitHub syntax to mark associated Issue(s) as resolved when this is merged into the default branch

- Resolves #347

### CODE REVIEW

File: R/step_lag_difference.R [hunk 1]
```diff
@@ -16,11 +16,12 @@
...
 #' r <- epi_recipe(case_death_rate_subset) %>%
-#'   step_lag_difference(case_rate, death_rate, horizon = c(7, 14))
+#'   step_lag_difference(case_rate, death_rate, horizon = c(7, 14)) %>%
+#'   step_epi_naomit()
 #' r
 #'
 #' r %>%
-#'   recipes::prep() %>%
+#'   recipes::prep(case_death_rate_subset) %>%
 #'   recipes::bake(case_death_rate_subset)
```
Comment (dajmcdon) [inline R/step_lag_difference.R:25]:
```suggestion
#'   prep(case_death_rate_subset) %>%
#'   bake(case_death_rate_subset)
```

Thanks! I'm not sure whether the prefixes are needed here (I think/hope not). May as well ditch them if possible at the same time.

**Review by dajmcdon — APPROVED** [review]

File: R/step_lag_difference.R (hunk 1 above)
Comment (dshemetov) [reply R/step_lag_difference.R:25]: Sure, seems to work
